### ISSUE TITLE
[ Feature ] 규정 고지 스크린 생성 

### ISSUE THREAD

**Issue by sillonjeu** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#15]
## 🛠 Issue
<img width="486" alt="스크린샷 2024-03-16 오후 4 31 06" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/b587bc98-bfb7-474e-a8f6-afd72dfede36">

## 📝 To-do

- [x] 3초 후 화면 넘어가는 로직 생성
- [x] 규정 고지 스크린 구현
- [x] 규정 고지 작성 완료 버튼 클릭 후 메인 스크린으로 넘어가기
