### ISSUE TITLE
[ Feature ] 채팅방 구현

### ISSUE THREAD

**Issue by bunju20** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#19]
## 🛠 Issue

<img width="320" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/85238126/d58bb976-d120-4698-8859-0d60691ca091">

## 📝 To-do

- [x] 상세화면에서 이동할수 있도록 구현
- [x] 스크린 뷰 구현
- [x] 더미 API로 확인
- [x] 아래 버튼 2개 추가
- [x] 입양신청서 버튼 누르면 해당 스크린으로 이동하게하기
