### ISSUE TITLE
[ Feature ] 채팅로그, 랜덤 매칭 스크린

### ISSUE THREAD

**Issue by bunju20** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#23]
## 🛠 Issue

<img width="276" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/85238126/74ed70f0-e92c-4a27-b113-6c52fa01686c">
<img width="268" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/85238126/46695e19-7bc7-419e-ae96-cef9db3246e5">

## 📝 To-do

- [x] if 채팅기록이 없다면 뷰 구현
- [x] API 더미 연동
- [x] if 채팅기록이 있다면
- [x] 랜덤으로 대화해보기
