### ISSUE TITLE
[ Feature ] 홈 터치 영역 수정, 홈, 상세페이지 좋아요 수정, 좋아요 스크린

### ISSUE THREAD

**Issue by bunju20** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#25]
## 🛠 Issue

<img width="203" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/85238126/bf0d7f4d-72df-4a82-baf2-5afa14dbb7da">

: 영역수정

<img width="395" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/85238126/253e2f3e-76b2-44a9-bfd1-14940b0fd82e">

: 바텀네비게이션 수정

<img width="223" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/85238126/6b837dea-344e-4133-8e68-0f2371654f2d">

위와 비슷하게 좋아요 스크린 생성.

## 📝 To-do

- [x] 홈 스크린 터치 영역 수정
- [x] 바텀네비게이션 수정
- [x] 채팅방에서 뒤로 안가지는 오류
- [ ] 홈, 상세페이지 좋아요 적용되게 수정 - 요거 아직 API 구현 안돼서 일단 냅두겠음!
- [x] 좋아요 스크린 생성
