### ISSUE TITLE
[ Feature ] 회원가입 스크린

### ISSUE THREAD

**Issue by sillonjeu** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#27]
## 🛠 Issue

<img width="584" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/98c5c14d-cf0d-45f2-a59e-7498a3ef531b">

## 📝 To-do

- [x] 입양자, 공고자 구분하기 스크린 구현 
- [x] 회원가입(아이디, 패스워드, 이메일, 전화번호 입력) 구현 
- [x] 로그인 api 연동
- [x] 회원가입 api 연동
