### ISSUE TITLE
[ Feature ] 입양 절차 api 연동 준비

### ISSUE THREAD

**Issue by sillonjeu** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#42]
## 🛠 Issue

<img width="1126" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/e1ddb4e1-8052-4ba9-984d-8a727811cd94">

## 📝 To-do

- [x] 입양 절차 MVVM 모델 완성
- [x] 입양 절차 api 연동
- [x] 입양 절차 디자인(색) 바꾸기
