### ISSUE TITLE
[ Feature ] 홈화면 상세페이지 API, 좋아요 API 연동

### ISSUE THREAD

**Issue by bunju20** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#45]
## 🛠 Issue

![CleanShot 2024-03-22 at 02 10 43@2x](https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/85238126/17e764a9-1cc3-4243-ba6e-30777ed1804d)

![CleanShot 2024-03-22 at 02 11 51@2x](https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/85238126/c33453d4-0f21-4085-bfdd-1e46c59b6886)

## 📝 To-do

- [x] 홈화면 상세페이지 API 연동
- [x] 홈화면 좋아요 생성 삭제 API연동
- [x] 좋아요 스크린 API 연동
- [x] 좋아요 스크린 좋아요 생성 삭제 API 연동
