### ISSUE TITLE
[ Feature ] 입양 신청/공고 페이지 service 수정, 마이페이지 api 연동 

### ISSUE THREAD

**Issue by sillonjeu** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#48]
## 🛠 Issue

<img width="326" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/c638a60b-d76a-4c5c-a15c-dfa546de83ee">

## 📝 To-do

- [x] 입양 신청 PostId, MemberId 받아오기로 수정 및 service 고치기
- [x] 마이페이지 api 연동
- [x] 공고 올리기 PostId 입력폼 추가하기
