### ISSUE TITLE
[ Feature, Fix ] 홈 화면 연동으로 바꾸기, 입양 신청 딜레이 수정

### ISSUE THREAD

**Issue by sillonjeu** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#55]
## 🛠 Issue

<img width="274" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/146772dd-d208-45c7-b4cc-8d6bc247ee98">
<img width="274" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/5e3b02cf-d5e0-456d-946e-a482a5c0e0ca">

## 📝 To-do

- [x] 홈 화면 이름 연동으로 바꾸기
- [x] 입양 신청 딜레이 수정
- [x] 공고 작성하기 스크린 메인이랑 잇기
