### ISSUE TITLE
[ Feature ] - 홈화면 스크린 생성

### ISSUE THREAD

**Issue by bunju20** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#7]
## 🛠 Issue

<img width="326" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/85238126/aebe4b85-d742-4ec3-88ca-a0976e82036a">

## 📝 To-do

- [x] 홈 스크린 뷰 생성
- [x] 만나서 반가워요 { }님 세팅
- [x] 무한스크롤 json으로 세팅.
- [ ] 거리순 정렬 구현 - 이건 다음에
