### ISSUE TITLE
[ Feature ] - 입양 신청서 스크린 생성

### ISSUE THREAD

**Issue by sillonjeu** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE#8]
## 🛠 Issue

<img width="642" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/379f9ba8-aed3-4e6b-82a0-31cfef67c940">
<img width="642" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/b131556e-7bda-44e0-8ec6-c7a81e3c9b3e">
<img width="642" alt="image" src="https://github.com/goormthon-Univ/2024_BEOTKKOTTHON_TEAM_9_FE/assets/59414536/93698292-83f7-488b-8144-faafd51e2bd0">

## 📝 To-do

- [x] 3초 뒤 넘어가는 뷰 생성
- [x] 각각 질문 폼 뷰 생성
- [x] json에 각각 차례대로 저장
- [x] 작성 완료 및 화면 넘어가기 구현
